go_import_path: github.com/cloudflare/alertmanager2es

sudo: false

services:
- docker

language: go

go:
- 1.7.x
- 1.8.x
- master

matrix:
  allow_failures:
  - go: master

script:
- make style test
# Build binaries
- make
